In [3]:
import pandas as pd

In [4]:
df = pd.read_table('https://github.com/prasertcbs/tutorial/raw/master/qnaire_fill_missing.tsv',index_col='obs',parse_dates=['dob'])
df

,gender,dob,salary,own_house,own_car,csi1,csi2,csi3,csi4,q1,q2,q3
obs,,,,,,,,,,,,
1,M,1997-09-17,223700.0,True,False,NaN,NaN,NaN,3.0,2.0,3.0,4
2,NaN,2001-01-16,121100.0,True,NaN,2.0,NaN,3.0,NaN,2.0,2.0,4
3,F,NaT,NaN,NaN,False,5.0,5.0,5.0,3.0,4.0,4.0,5
4,F,1995-12-04,79900.0,False,NaN,NaN,5.0,4.0,1.0,NaN,3.0,5
5,M,2001-04-12,32800.0,False,True,4.0,1.0,NaN,2.0,3.0,2.0,4
6,F,NaT,NaN,True,False,5.0,NaN,2.0,NaN,1.0,NaN,3
7,NaN,2002-12-13,272500.0,False,False,1.0,1.0,NaN,2.0,3.0,4.0,3
8,NaN,1999-07-24,41600.0,False,False,1.0,4.0,1.0,NaN,NaN,NaN,5
9,M,2003-02-20,141300.0,True,False,2.0,NaN,4.0,3.0,1.0,4.0,2
10,M,1995-09-26,68000.0,True,False,4.0,5.0,NaN,3.0,2.0,1.0,2

In [5]:
df.shape

(10, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 1 to 10
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   gender     7 non-null      object
 1   dob        8 non-null      datetime64[ns]
 2   salary     8 non-null      float64
 3   own_house  9 non-null      object
 4   own_car    8 non-null      object
 5   csi1       8 non-null      float64
 6   csi2       6 non-null      float64
 7   csi3       6 non-null      float64
 8   csi4       7 non-null      float64
 9   q1         8 non-null      float64
 10  q2         8 non-null      float64
 11  q3         10 non-null     int64
dtypes: datetime64[ns](1), float64(7), int64(1), object(3)
memory usage: 1.0+ KB

In [7]:
df.isnull()

,gender,dob,salary,own_house,own_car,csi1,csi2,csi3,csi4,q1,q2,q3
obs,,,,,,,,,,,,
1,False,False,False,False,False,True,True,True,False,False,False,False
2,True,False,False,False,True,False,True,False,True,False,False,False
3,False,True,True,True,False,False,False,False,False,False,False,False
4,False,False,False,False,True,True,False,False,False,True,False,False
5,False,False,False,False,False,False,False,True,False,False,False,False
6,False,True,True,False,False,False,True,False,True,False,True,False
7,True,False,False,False,False,False,False,True,False,False,False,False
8,True,False,False,False,False,False,False,False,True,True,True,False
9,False,False,False,False,False,False,True,False,False,False,False,False
10,False,False,False,False,False,False,False,True,False,False,False,False

In [9]:
df.salary.isnull().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of obs
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10    False
Name: salary, dtype: bool>

In [10]:
df.describe()

,salary,csi1,csi2,csi3,csi4,q1,q2,q3
count,8.000000,8.000000,6.000000,6.000000,7.000000,8.000000,8.000000,10.000000
mean,122612.500000,3.000000,3.500000,3.166667,2.428571,2.250000,2.875000,3.700000
std,86579.978509,1.690309,1.974842,1.471960,0.786796,1.035098,1.125992,1.159502
min,32800.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000
25%,61400.000000,1.750000,1.750000,2.250000,2.000000,1.750000,2.000000,3.000000
50%,100500.000000,3.000000,4.500000,3.500000,3.000000,2.000000,3.000000,4.000000
75%,161900.000000,4.250000,5.000000,4.000000,3.000000,3.000000,4.000000,4.750000
max,272500.000000,5.000000,5.000000,5.000000,3.000000,4.000000,4.000000,5.000000

In [11]:
df.salary.fillna(100500,inplace=True)

In [13]:
df.own_car.value_counts()

False    7
True     1
Name: own_car, dtype: int64

In [15]:
df.own_car.fillna(False,inplace=True)
df

,gender,dob,salary,own_house,own_car,csi1,csi2,csi3,csi4,q1,q2,q3
obs,,,,,,,,,,,,
1,M,1997-09-17,223700.0,True,False,NaN,NaN,NaN,3.0,2.0,3.0,4
2,NaN,2001-01-16,121100.0,True,False,2.0,NaN,3.0,NaN,2.0,2.0,4
3,F,NaT,100500.0,NaN,False,5.0,5.0,5.0,3.0,4.0,4.0,5
4,F,1995-12-04,79900.0,False,False,NaN,5.0,4.0,1.0,NaN,3.0,5
5,M,2001-04-12,32800.0,False,True,4.0,1.0,NaN,2.0,3.0,2.0,4
6,F,NaT,100500.0,True,False,5.0,NaN,2.0,NaN,1.0,NaN,3
7,NaN,2002-12-13,272500.0,False,False,1.0,1.0,NaN,2.0,3.0,4.0,3
8,NaN,1999-07-24,41600.0,False,False,1.0,4.0,1.0,NaN,NaN,NaN,5
9,M,2003-02-20,141300.0,True,False,2.0,NaN,4.0,3.0,1.0,4.0,2
10,M,1995-09-26,68000.0,True,False,4.0,5.0,NaN,3.0,2.0,1.0,2

In [18]:
df.fillna(df.mean()['csi1':'q3'],inplace=True)
df

<ipython-input-18-bf29016b14ff>:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  df.fillna(df.mean()['csi1':'q3'],inplace=True)
<ipython-input-18-bf29016b14ff>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean()['csi1':'q3'],inplace=True)

,gender,dob,salary,own_house,own_car,csi1,csi2,csi3,csi4,q1,q2,q3
obs,,,,,,,,,,,,
1,M,1997-09-17,223700.0,True,False,3.0,3.5,3.166667,3.000000,2.00,3.000,4
2,NaN,2001-01-16,121100.0,True,False,2.0,3.5,3.000000,2.428571,2.00,2.000,4
3,F,NaT,100500.0,NaN,False,5.0,5.0,5.000000,3.000000,4.00,4.000,5
4,F,1995-12-04,79900.0,False,False,3.0,5.0,4.000000,1.000000,2.25,3.000,5
5,M,2001-04-12,32800.0,False,True,4.0,1.0,3.166667,2.000000,3.00,2.000,4
6,F,NaT,100500.0,True,False,5.0,3.5,2.000000,2.428571,1.00,2.875,3
7,NaN,2002-12-13,272500.0,False,False,1.0,1.0,3.166667,2.000000,3.00,4.000,3
8,NaN,1999-07-24,41600.0,False,False,1.0,4.0,1.000000,2.428571,2.25,2.875,5
9,M,2003-02-20,141300.0,True,False,2.0,3.5,4.000000,3.000000,1.00,4.000,2
10,M,1995-09-26,68000.0,True,False,4.0,5.0,3.166667,3.000000,2.00,1.000,2

In [23]:
df.dob.fillna(pd.to_datetime('1995-04-13'),inplace=True)
df

,gender,dob,salary,own_house,own_car,csi1,csi2,csi3,csi4,q1,q2,q3
obs,,,,,,,,,,,,
1,M,1997-09-17,223700.0,True,False,3.0,3.5,3.166667,3.000000,2.00,3.000,4
2,NaN,2001-01-16,121100.0,True,False,2.0,3.5,3.000000,2.428571,2.00,2.000,4
3,F,1995-04-13,100500.0,NaN,False,5.0,5.0,5.000000,3.000000,4.00,4.000,5
4,F,1995-12-04,79900.0,False,False,3.0,5.0,4.000000,1.000000,2.25,3.000,5
5,M,2001-04-12,32800.0,False,True,4.0,1.0,3.166667,2.000000,3.00,2.000,4
6,F,1995-04-13,100500.0,True,False,5.0,3.5,2.000000,2.428571,1.00,2.875,3
7,NaN,2002-12-13,272500.0,False,False,1.0,1.0,3.166667,2.000000,3.00,4.000,3
8,NaN,1999-07-24,41600.0,False,False,1.0,4.0,1.000000,2.428571,2.25,2.875,5
9,M,2003-02-20,141300.0,True,False,2.0,3.5,4.000000,3.000000,1.00,4.000,2
10,M,1995-09-26,68000.0,True,False,4.0,5.0,3.166667,3.000000,2.00,1.000,2

In [25]:
df.gender.fillna('missing',inplace=True)
df

,gender,dob,salary,own_house,own_car,csi1,csi2,csi3,csi4,q1,q2,q3
obs,,,,,,,,,,,,
1,M,1997-09-17,223700.0,True,False,3.0,3.5,3.166667,3.000000,2.00,3.000,4
2,missing,2001-01-16,121100.0,True,False,2.0,3.5,3.000000,2.428571,2.00,2.000,4
3,F,1995-04-13,100500.0,NaN,False,5.0,5.0,5.000000,3.000000,4.00,4.000,5
4,F,1995-12-04,79900.0,False,False,3.0,5.0,4.000000,1.000000,2.25,3.000,5
5,M,2001-04-12,32800.0,False,True,4.0,1.0,3.166667,2.000000,3.00,2.000,4
6,F,1995-04-13,100500.0,True,False,5.0,3.5,2.000000,2.428571,1.00,2.875,3
7,missing,2002-12-13,272500.0,False,False,1.0,1.0,3.166667,2.000000,3.00,4.000,3
8,missing,1999-07-24,41600.0,False,False,1.0,4.0,1.000000,2.428571,2.25,2.875,5
9,M,2003-02-20,141300.0,True,False,2.0,3.5,4.000000,3.000000,1.00,4.000,2
10,M,1995-09-26,68000.0,True,False,4.0,5.0,3.166667,3.000000,2.00,1.000,2